{
    "name": "Splendid Accounts Sync",
    "summary": "Import Splendid accounting with source-controlled taxes, Anglo-Saxon Vendor Bill repair, JournalEntries/Expenses migration, and fixed-cost Manufacturing Work Orders",
    "version": "18.0.5.39.0",
    "category": "Accounting/Accounting",
    "author": "Devix Technology",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "account",
        "product",
        "uom",
        "stock",
        "sale_management",
        "sale_stock",
        "purchase",
        "purchase_stock",
        "mrp",
        "mrp_account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/splendid_views.xml",
        "views/splendid_end_to_end_views.xml",
        "views/mrp_production_views.xml",
        "data/ir_cron.xml",
    ],
    "installable": True,
    "application": True,
}
