# -*- coding: utf-8 -*-
{
    "name": "House of Amin FMCG Brand Reporting",
    "summary": "Company controlled FMCG brand analytics using existing Geo Region/Zone/Town masters",
    "version": "18.0.1.0.3",
    "category": "Accounting/Accounting",
    "author": "Ideabox Technology",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "product",
        "stock",
        "sale_management",
        "purchase",
        "account",
        "analytic",
        "hr_expense",
        "odoo_genics_x_amin_enterprise_ext",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/product_attribute_packaging_data.xml",
        "views/menu_views.xml",
        "views/fmcg_master_views.xml",
        "views/res_company_views.xml",
        "views/product_views.xml",
        "views/res_partner_views.xml",
        "views/sale_views.xml",
        "views/purchase_views.xml",
        "views/account_move_views.xml",
        "views/hr_expense_views.xml",
        "views/stock_views.xml",
        "views/report_views.xml",
    ],
    "installable": True,
    "application": False,
}
