from . import splendid_sync_map
from . import splendid_sync_log
from . import splendid_connection
from . import res_partner
from . import product_template
from . import account_account
from . import account_move
from . import account_payment
from . import stock_warehouse
from . import stock_picking
from . import mrp_production
