from . import splendid_sync_map
from . import splendid_sync_log
from . import res_partner
from . import product_template
from . import account_account
from . import stock_warehouse
from . import account_journal
from . import account_tax
from . import splendid_connection
from . import sale_order
from . import purchase_order
from . import account_move
from . import account_payment
from . import stock_picking

from . import mrp_production
from . import mrp_bom
from . import splendid_job_order_expense
from . import mrp_workcenter
from . import mrp_routing_workcenter
from . import mrp_workorder
from . import mrp_report_mo_overview
